### ISSUE TITLE
说明文档的运行步骤缺少

### ISSUE THREAD

**Issue by Dadashuai1042** [Edapinenut/GeoAB#3]
非常感谢您的开源，很优秀的工作，但是在运行代码时，我有一个疑问，程序的输入输出是什么，说明文档的运行步骤中只有train和evaluation，能够根据自己输入的抗原生成抗体吗

**Comment by Dadashuai1042** [comment]
followed the instructions and run
python train_refine.py
and it gave me an error like the following, please help, Thanks!

Traceback (most recent call last):
  File "/home/disk02/ab_design/ys/ab_design/GeoAB/train_refine.py", line 214, in <module>
    result = exp.k_fold_train_eval(args.tag) if args.k_fold_eval else exp.train_eval(args.tag)
  File "/home/disk02/ab_design/ys/ab_design/GeoAB/train_refine.py", line 102, in train_eval
    train_loader, valid_loader, model = self._get_data_and_model(os.path.join(data_dir, 'train.json'), 
  File "/home/disk02/ab_design/ys/ab_design/GeoAB/train_refine.py", line 49, in _get_data_and_model
    n_channel = valid_set[0]['X'].shape[1]
  File "/home/disk02/ab_design/ys/ab_design/GeoAB/dataset/dataset.py", line 401, in __getitem__
    antigen_chains = item.get_antigen_chains(interface_only=True, cdr=None)
AttributeError: 'AgAbComplex' object has no attribute 'get_antigen_chains'. Did you mean: 'get_light_chain'?

**Comment by EDAPINENUT** [comment]
你好 暂且还没有开放相关功能。From Lin Haitao’s iphone.在 2024年7月25日，09:15，Dadashuai1042 ***@***.***> 写道：﻿
非常感谢您的开源，很优秀的工作，但是在运行代码时，我有一个疑问，程序的输入输出是什么，说明文档的运行步骤中只有train和evaluation，能够根据自己输入的抗原生成抗体吗
